#!/bin/dash

gitr_path=$(readlink -f $0)
gitr_path=$(dirname $gitr_path)
if echo "$PATH" | grep -E "$gitr_path" >/dev/null
then :
else
    echo "Would you like to temporarily(1) or permanently(2) add $gitr_path to PATH?\nEnter 1 or 2:"
fi

if test $# -ge 1
then
    echo "usage: gitr-init" 1>&2
    exit 1
elif test -d '.gitr'
then
    echo "gitr-init: error: .gitr already exists" 1>&2
    exit 1
else
    mkdir '.gitr' '.gitr/branches' '.gitr/objects' '.gitr/objects/commits' '.gitr/objects/blobs' 
    touch '.gitr/index' 
    touch '.gitr/previous_index'
    echo '0' > '.gitr/branches/master' # Master branch will start off with head pointing to commit 0
    echo '.gitr/branches/master' > '.gitr/HEAD' # Make head point to master branch
    echo '-1' > '.gitr/commit_ID_tracker' # Keep track of the latest commit ID
    echo "Initialized empty gitr repository in .gitr"
fi
